### ISSUE TITLE
Fix licensing

### ISSUE THREAD

**Issue by jbicha** [mate-desktop/mate-icon-theme-faenza#21]
This project includes materials from the Faenza icon theme. The Faenza icon theme is GPL-3. (I've not seen any clear evidence that it is GPL-3+).

But your COPYING file is the text of the GPL-2.

Please include more specific and accurate licensing information in your project.

**Comment by raveit65** [comment]
I don't use that theme, should we drop it?

**Comment by lukefromdc** [comment]
I don' use it either but surely some people do. I have no issues with changing the license but if any contributors do we would have to drop it. Personally I rather like the GPL3, due to the ban on "tivoization" or using the code in proprietary devices engineered to block or attempt to block users from running modified code e.g Tivo, xbox, iphone, etc.

**Comment by monsta** [comment]
@jbicha: how do we re-license the repo? Just replace our `COPYING` with a new one (like the one from https://choosealicense.com/licenses/gpl-3.0/)?

**Comment by jbicha** [comment]
Yes, but make sure that no one that has contributed to your project has a problem with the project being GPL-3. Please also specifically mention the license in at least the README.
